---
fastapi_app_dir: /opt/fastapi-tutorial
fastapi_port: 8000
fastapi_repo_url: https://github.com/dibanez/fastapi_tutorial.git
fastapi_repo_version: main
python_venv_path: "{{ fastapi_app_dir }}/venv"
required_packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - postgresql
  - postgresql-contrib
  - libpq-dev
service_name: fastapi-tutorial
