---
galaxy_info:
  role_name: fastapi_tutorial
  namespace: x2a
  author: Chef Example
  description: Configures FastAPI tutorial application with PostgreSQL
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: EL
      versions:
        - "7"
        - "8"
  galaxy_tags:
    - fastapi
    - python
    - web
    - postgresql
dependencies: []
