---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
- name: reload sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-security.conf
  changed_when: true
- name: restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
