---
- name: Install SSL packages
  ansible.builtin.package:
    name:
      - openssl
      - ca-certificates
    state: present
- name: Create ssl-cert group
  ansible.builtin.group:
    name: ssl-cert
    state: present
- name: Create SSL certificate directory
  ansible.builtin.file:
    path: "{{ nginx_ssl_certificate_path }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
- name: Create SSL private key directory
  ansible.builtin.file:
    path: "{{ nginx_ssl_private_key_path }}"
    owner: root
    group: ssl-cert
    mode: "0710"
    state: directory
- name: Check if SSL certificates exist
  ansible.builtin.stat:
    path: "{{ nginx_ssl_certificate_path }}/{{ item.key }}.crt"
  register: ssl_cert_exists
  loop: "{{ nginx_sites | dict2items }}"
  when: item.value.ssl | bool
- name: Check if SSL keys exist
  ansible.builtin.stat:
    path: "{{ nginx_ssl_private_key_path }}/{{ item.key }}.key"
  register: ssl_key_exists
  loop: "{{ nginx_sites | dict2items }}"
  when: item.value.ssl | bool
- name: Generate self-signed SSL certificates
  ansible.builtin.shell: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 \

    -keyout {{ nginx_ssl_private_key_path }}/{{ item.item.key }}.key \

    -out {{ nginx_ssl_certificate_path }}/{{ item.item.key }}.crt \

    -subj "/C=US/ST=Example/L=Example/O=Example Org/OU=IT/CN={{ item.item.key }}/emailAddress=admin@example.com"

    chmod 640 {{ nginx_ssl_private_key_path }}/{{ item.item.key }}.key

    chown root:ssl-cert {{ nginx_ssl_private_key_path }}/{{ item.item.key }}.key

    '
  args:
    creates: "{{ nginx_ssl_certificate_path }}/{{ item.item.key }}.crt"
  loop: "{{ ssl_cert_exists.results }}"
  when:
    - item.item.value.ssl | bool
    - not item.stat.exists
  notify: reload nginx
