---
nginx_ssl_certificate_path: /etc/ssl/certs
nginx_ssl_private_key_path: /etc/ssl/private
security_ssh_disable_root: true
security_ssh_password_auth: false
nginx_sites:
  example.com:
    document_root: /var/www/example.com
    ssl: true
  test.example.com:
    document_root: /var/www/test.example.com
    ssl: false
