---
controller_credential_types:
- name: PostgreSQL Database
  description: Credential type for PostgreSQL Database
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Database Username
      help_text: PostgreSQL database username for FastAPI application
    - id: password
      type: string
      label: Database Password
      secret: true
      help_text: PostgreSQL database user password for database connection
    - id: database_name
      type: string
      label: Database Name
      help_text: PostgreSQL database name for FastAPI application
    - id: host
      type: string
      label: Database Host
      help_text: PostgreSQL database host address
    required:
    - username
    - password
    - database_name
    - host
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      database_name: !unsafe '{{ database_name }}'
      host: !unsafe '{{ host }}'
