---
controller_credentials:
- name: PostgreSQL Database - fastapi_tutorial
  description: Credential for fastapi_tutorial
  organization: Default
  credential_type: PostgreSQL Database
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    database_name: '{{ database_name }}'
    host: '{{ host }}'
